
# Syntax highlighting
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: /:title

# Setup
timezone: "Asia/Ulaanbaatar" # eg. Asia/Kathmandu
locale: "mn" # eg. en_us
name: "Nomadic Method"
title: "Nomadic Method"
tagline: "Nomadic Method is where Tourism meets Innovation."
description: "Nomadic Method is where Tourism meets Innovation."
url: "https://nomadicmethod.rocks"
# rss: "Nomadic Method RSS feed URL"
baseurl: "/"
baseurl_posts_img: "/assets/images/posts/"
baseurl_featured_img: "/assets/images/hero/"
baseurl_featured_thumbnail: "/assets/images/hero/"
baseurl_javascripts: "/assets/javascripts/"
icon: "/assets/images/thumbnail/nomadicmethod.png" # /assets/img/icon.png [best 300px X 300px]
# disqus: "disqus_shortname" # get it on https://disqus.com/admin/

author:
  name: "Nomadic Method"
  url: "https://nomadicmethod.rocks"
  facebook: "nomadicmethod"
  twitter: "nomadic_method"
  # google_plus: username
  linkedin: "nomadicmethod"
  # dribbble: username
  # pinterest: username
  # kiva: username

# fb_admins: your facebook profile id
# fb_appid: your facebook app id

# Server
destination: ./_site
exclude: [".editorconfig", ".gitignore", "bower.json", "composer.json", "CONTRIBUTING.md", "CNAME", "LICENSE", "Gruntfile.js", "package.json", "node_modules", "README.md", "sass", "haml"]
port: 9001

defaults:
  -
    scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "default"
